source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XBLocation_Example', :exclusive => true do
  pod "XBLocation", :path => "../"
end

target 'XBLocation_Tests', :exclusive => true do
  pod "XBLocation", :path => "../"

  pod 'FBSnapshotTestCase'
end
